include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cr881x-wan-mode
PKG_VERSION:=1
PKG_RELEASE:=1

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=zcop

LUCI_TITLE:=LuCI support for CR881x WAN mode switching
LUCI_DEPENDS:=+luci-base +rpcd +rpcd-mod-ucode

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
